### ISSUE TITLE
App crashes on startup: FileNotFoundError

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#1]
Here is the stack trace:

```
/home/satochip/Documents/github/satochip_utils/venv/bin/python /home/satochip/Documents/github/satochip_utils/satochip_utils.py 
2024-05-15 15:54:58 - [satochip_utils.py:22] - INFO - __main__ - <module>() - loglevel: 20
2024-05-15 15:54:58 - [view.py:33] - INFO - view - __init__() - controller
2024-05-15 15:54:58 - [view.py:35] - INFO - view - __init__() - controller as bridge to card connector
2024-05-15 15:54:58 - [view.py:55] - INFO - view - __init__() - UI in welcome view
2024-05-15 15:54:58 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
2024-05-15 15:54:59 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
2024-05-15 15:54:59 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:043abfed8f431145510fd90b7d7c936082a01ea1a1cb849ecea96daa35d987187b0364fad4f2d28cc31a65015dcf3c35cef50b0220f23b3c6a71c31d17587b0d4b
2024-05-15 15:54:59 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
2024-05-15 15:54:59 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
2024-05-15 15:54:59 - [CardConnector.py:65] - INFO - pysatochip.pysatochip.CardConnector - update() - disconnecting from'Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00'
2024-05-15 15:54:59 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
2024-05-15 15:55:00 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:043565af84ed476cceab557d6f8bfefbc5baa0c3cb605c9c7378d076be89984e68bed30514376c2575d6b0e9401802ca1e482c01c3dcc8678590c351d9b1b95f00
2024-05-15 15:55:00 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
2024-05-15 15:55:02 - [controller.py:110] - INFO - controller - handle_user_action() - In handle_user_action:
2024-05-15 15:55:02 - [controller.py:94] - INFO - controller - request() - Controller request: start_setup
2024-05-15 15:55:02 - [view.py:87] - INFO - view - clear_current_frame() - In clear_current_frame
/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py:179: UserWarning: CTkButton Warning: Given image is not CTkImage but <class 'PIL.ImageTk.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead.

  warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
2024-05-15 15:55:02 - [view.py:273] - INFO - view - main_menu() - Card detected
2024-05-15 15:55:02 - [view.py:298] - INFO - view - main_menu() - setup done
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 527, in <lambda>
    command=lambda: self.controller.handle_user_action(frame_name, button_label))
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 123, in handle_user_action
    self.request("start_setup")
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
    reply = method_to_call(*args)
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 550, in start_setup
    self.main_menu()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 376, in main_menu
    self.create_button_for_main_menu_item(
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 167, in create_button_for_main_menu_item
    image = Image.open(icon_path)
  File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/PIL/Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/satochip/Documents/github/satochip_utils/pictures_db/icon_refresh.png'
```

**Comment by Tech-Aware** [comment]
I'm quickly thanks

**Comment by Tech-Aware** [comment]
Normaly this is resolved by adding pictures that miss in the right  folder into the repositories. It isnt't ?

**Comment by Toporin** [comment]
> Normaly this is resolved by adding pictures that miss in the right folder into the repositories. It isnt't ?

Yes, you need to add the missing image in the folder :-)
