### ISSUE TITLE
App freeze when no card is inserted

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#2]
When no card is inserted, a popup appears (with no text) and app does not respond

Here is the printscreen:
![Screenshot from 2024-05-15 15-51-50](https://github.com/Tech-Aware/satochip_utils/assets/10826856/905cbb3e-da51-4404-9999-33ccd374712b)

Here is the stack trace:

```
/home/satochip/Documents/github/satochip_utils/venv/bin/python /home/satochip/Documents/github/satochip_utils/satochip_utils.py 
2024-05-15 10:47:15 - [satochip_utils.py:22] - INFO - __main__ - <module>() - loglevel: 20
2024-05-15 10:47:16 - [view.py:33] - INFO - view - __init__() - controller
2024-05-15 10:47:16 - [view.py:35] - INFO - view - __init__() - controller as bridge to card connector
2024-05-15 10:47:16 - [view.py:55] - INFO - view - __init__() - UI in welcome view
2024-05-15 10:47:23 - [controller.py:110] - INFO - controller - handle_user_action() - In handle_user_action:
2024-05-15 10:47:23 - [controller.py:94] - INFO - controller - request() - Controller request: start_setup
2024-05-15 10:47:23 - [view.py:87] - INFO - view - clear_current_frame() - In clear_current_frame
/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py:179: UserWarning: CTkButton Warning: Given image is not CTkImage but <class 'PIL.ImageTk.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead.

  warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
2024-05-15 10:47:23 - [view.py:276] - INFO - view - main_menu() - Card undetected
2024-05-15 10:47:23 - [view.py:222] - INFO - view - show() - Popup: WARNING | Menu had been disabled: Card undetected
 Please, insert a Card and click <OK!>
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 527, in <lambda>
    command=lambda: self.controller.handle_user_action(frame_name, button_label))
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 123, in handle_user_action
    self.request("start_setup")
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
    reply = method_to_call(*args)
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 550, in start_setup
    self.main_menu()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 278, in main_menu
    self.show("WARNING",
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 232, in show
    popup.grab_set()  # Grab all events
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 902, in grab_set
    self.tk.call('grab', 'set', self._w)
_tkinter.TclError: grab failed: window not viewable
2024-05-15 15:52:30 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
2024-05-15 15:52:30 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
2024-05-15 15:52:30 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:041ee1dcefb8f3101dea6eb830e6c7f8d971a0a544c3af3242f554278aa581de2db0ad5f0716ce36643f536e9f837ee535a5c349361f0ee0e3b13290d781ca557b
2024-05-15 15:52:31 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
2024-05-15 15:52:31 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
2024-05-15 15:52:31 - [CardConnector.py:65] - INFO - pysatochip.pysatochip.CardConnector - update() - disconnecting from'Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00'
2024-05-15 15:52:31 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
2024-05-15 15:52:31 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:04f8deb4ca206b096938f0f91bf6dfebc419c0ed6df863aad848dc256b92ae31518bf38f68f6f03c7f1b90d2b5e3c50cbe1e9e8dd5cb92552635e952b59d4164b9
2024-05-15 15:52:31 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
2024-05-15 15:53:14 - [CardConnector.py:287] - INFO - pysatochip.pysatochip.CardConnector - card_disconnect() - In card_disconnect()
2024-05-15 15:53:14 - [CardConnector.py:65] - INFO - pysatochip.pysatochip.CardConnector - update() - disconnecting from'Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00'
2024-05-15 15:53:14 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
```

**Comment by Tech-Aware** [comment]
I need to explore it, thanks

**Comment by Tech-Aware** [comment]
> When no card is inserted, a popup appears (with no text) and app does not respond
> 
> Here is the printscreen:
> ![Screenshot from 2024-05-15 15-51-50](https://github.com/Tech-Aware/satochip_utils/assets/10826856/905cbb3e-da51-4404-9999-33ccd374712b)
> 
> Here is the stack trace:
> 
> ```
> /home/satochip/Documents/github/satochip_utils/venv/bin/python /home/satochip/Documents/github/satochip_utils/satochip_utils.py 
> 2024-05-15 10:47:15 - [satochip_utils.py:22] - INFO - __main__ - <module>() - loglevel: 20
> 2024-05-15 10:47:16 - [view.py:33] - INFO - view - __init__() - controller
> 2024-05-15 10:47:16 - [view.py:35] - INFO - view - __init__() - controller as bridge to card connector
> 2024-05-15 10:47:16 - [view.py:55] - INFO - view - __init__() - UI in welcome view
> 2024-05-15 10:47:23 - [controller.py:110] - INFO - controller - handle_user_action() - In handle_user_action:
> 2024-05-15 10:47:23 - [controller.py:94] - INFO - controller - request() - Controller request: start_setup
> 2024-05-15 10:47:23 - [view.py:87] - INFO - view - clear_current_frame() - In clear_current_frame
> /home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py:179: UserWarning: CTkButton Warning: Given image is not CTkImage but <class 'PIL.ImageTk.PhotoImage'>. Image can not be scaled on HighDPI displays, use CTkImage instead.
> 
>   warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
> 2024-05-15 10:47:23 - [view.py:276] - INFO - view - main_menu() - Card undetected
> 2024-05-15 10:47:23 - [view.py:222] - INFO - view - show() - Popup: WARNING | Menu had been disabled: Card undetected
>  Please, insert a Card and click <OK!>
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
>     return self.func(*args)
>   File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
>     self._command()
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 527, in <lambda>
>     command=lambda: self.controller.handle_user_action(frame_name, button_label))
>   File "/home/satochip/Documents/github/satochip_utils/controller.py", line 123, in handle_user_action
>     self.request("start_setup")
>   File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
>     reply = method_to_call(*args)
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 550, in start_setup
>     self.main_menu()
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 278, in main_menu
>     self.show("WARNING",
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 232, in show
>     popup.grab_set()  # Grab all events
>   File "/usr/local/lib/python3.8/tkinter/__init__.py", line 902, in grab_set
>     self.tk.call('grab', 'set', self._w)
> _tkinter.TclError: grab failed: window not viewable
> 2024-05-15 15:52:30 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
> 2024-05-15 15:52:30 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
> 2024-05-15 15:52:30 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:041ee1dcefb8f3101dea6eb830e6c7f8d971a0a544c3af3242f554278aa581de2db0ad5f0716ce36643f536e9f837ee535a5c349361f0ee0e3b13290d781ca557b
> 2024-05-15 15:52:31 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
> 2024-05-15 15:52:31 - [CardConnector.py:94] - INFO - pysatochip.pysatochip.CardConnector - update() - +Inserted: 3B FA 18 00 00 81 31 FE 45 4A 54 61 78 43 6F 72 65 56 31 B2
> 2024-05-15 15:52:31 - [CardConnector.py:65] - INFO - pysatochip.pysatochip.CardConnector - update() - disconnecting from'Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00'
> 2024-05-15 15:52:31 - [CardConnector.py:1468] - INFO - pysatochip.pysatochip.CardConnector - card_initiate_secure_channel() - In card_initiate_secure_channel()
> 2024-05-15 15:52:31 - [CardDataParser.py:161] - INFO - pysatochip.pysatochip.CardDataParser - parse_initiate_secure_channel() - In parse_initiate_secure_channel: successfuly recovered pubkey:04f8deb4ca206b096938f0f91bf6dfebc419c0ed6df863aad848dc256b92ae31518bf38f68f6f03c7f1b90d2b5e3c50cbe1e9e8dd5cb92552635e952b59d4164b9
> 2024-05-15 15:52:31 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
> 2024-05-15 15:53:14 - [CardConnector.py:287] - INFO - pysatochip.pysatochip.CardConnector - card_disconnect() - In card_disconnect()
> 2024-05-15 15:53:14 - [CardConnector.py:65] - INFO - pysatochip.pysatochip.CardConnector - update() - disconnecting from'Generic Smart Card Reader Interface [Smart Card Reader Interface] (20070818000000000) 00 00'
> 2024-05-15 15:53:14 - [controller.py:94] - INFO - controller - request() - Controller request: update_status
> ```

It is solved ?
