### ISSUE TITLE
UI issue when displaying error popup

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#7]
When an error arises, the popup error window freeze and the message is not shown correctly.
When the issue happens, the popup freeze and it is not possible to close it.

![Screenshot from 2024-05-16 15-10-37](https://github.com/Tech-Aware/satochip_utils/assets/10826856/e30b6051-81ae-4481-ad1f-ddb1c881b138)

stack trace:
```
  warnings.warn(f"{type(self).__name__} Warning: Given image is not CTkImage but {type(image)}. Image can not be scaled on HighDPI displays, use CTkImage instead.\n")
2024-05-16 15:06:14 - [view.py:179] - DEBUG - view - create_entry() - with secure write
2024-05-16 15:06:14 - [view.py:179] - DEBUG - view - create_entry() - with secure write
2024-05-16 15:06:14 - [view.py:179] - DEBUG - view - create_entry() - with secure write
2024-05-16 15:06:14 - [view.py:152] - DEBUG - view - create_button() - without command
2024-05-16 15:06:14 - [view.py:158] - DEBUG - view - create_button() - with command
2024-05-16 15:06:14 - [view.py:158] - DEBUG - view - create_button() - with command
2024-05-16 15:06:28 - [controller.py:110] - INFO - controller - handle_user_action() - In handle_user_action:
2024-05-16 15:06:28 - [controller.py:119] - INFO - controller - handle_user_action() - frame concerned = change_pin, button_clicked = Finish, entry_value = 1234 12345 12345
2024-05-16 15:06:28 - [controller.py:236] - INFO - controller - handle_user_action() - in change_pin
2024-05-16 15:06:28 - [CardConnector.py:1377] - INFO - pysatochip.pysatochip.CardConnector - card_change_PIN() - In card_change_PIN
2024-05-16 15:06:28 - [CardConnector.py:206] - DEBUG - pysatochip.pysatochip.CardConnector - card_transmit() - In card_transmit
2024-05-16 15:06:28 - [CardConnector.py:1491] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - In card_encrypt_secure_channel()
2024-05-16 15:06:28 - [CardConnector.py:1502] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - Plaintext C-APDU: B0 44 00 00 0B * * * * * * * * * * *
2024-05-16 15:06:28 - [SecureChannel.py:63] - DEBUG - pysatochip.pysatochip.SecureChannel - encrypt_secure_channel() - In encrypt_secure_channel()
2024-05-16 15:06:28 - [CardConnector.py:73] - DEBUG - pysatochip.pysatochip.CardConnector - update() - > B0 82 00 00 48 BC FA 56 E5 C0 10 57 59 89 49 B5 6F 00 00 00 0F 00 20 DC 8E 72 D9 BA 6A D6 DB C1 97 0B 6B B4 F0 E3 B9 6F BF 7E 70 93 26 44 DF 7A AF 38 04 B7 F9 CE C5 00 14 2F 09 35 DD 3B C5 F9 F4 07 A8 06 0E 04 63 54 2E 55 66 BA 91
2024-05-16 15:06:28 - [CardConnector.py:76] - DEBUG - pysatochip.pysatochip.CardConnector - update() - < [] 63 C4
2024-05-16 15:06:28 - [controller.py:94] - INFO - controller - request() - Controller request: show
2024-05-16 15:06:28 - [view.py:222] - INFO - view - show() - Popup: ERROR | Wrong PIN! 4 tries remaining!
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 831, in <lambda>
    [self.controller.handle_user_action(frame_name, "Finish",
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 249, in handle_user_action
    (response, sw1, sw2) = self.cc.card_change_PIN(0, current_pin, new_pin)
  File "/home/satochip/Documents/github/satochip_utils/pysatochip/pysatochip/CardConnector.py", line 1396, in card_change_PIN
    self.client.request('show', 'ERROR', msg)
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
    reply = method_to_call(*args)
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 232, in show
    popup.grab_set()  # Grab all events
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 902, in grab_set
    self.tk.call('grab', 'set', self._w)
_tkinter.TclError: grab failed: window not viewable
```

**Comment by Tech-Aware** [comment]
I dont have this error in my windows distribution, do you use windows too or another Os ? 
as i'm not encountering the problem it's a little bit hard to solve, cause i depend of your feedback to know if it's good actually ?

**Comment by Toporin** [comment]
I am running app from sources using pycharm in venv environment, python 3.8 on linux Ubuntu 20.04

**Comment by Tech-Aware** [comment]
> I am running app from sources using pycharm in venv environment, python 3.8 on linux Ubuntu 20.04

It is solved ?
