### ISSUE TITLE
Error during change PIN when card is blocked

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/satochip_utils#8]
error: " AttributeError: '_tkinter.tkapp' object has no attribute 'show, ERROR' "

stack trace:
```
2024-05-16 15:13:47 - [controller.py:94] - INFO - controller - request() - Controller request: change_pin
2024-05-16 15:13:47 - [CardConnector.py:1310] - INFO - pysatochip.pysatochip.CardConnector - card_verify_PIN() - In card_verify_PIN
2024-05-16 15:13:47 - [controller.py:274] - INFO - controller - PIN_dialog() - In PIN dialog
2024-05-16 15:13:47 - [controller.py:94] - INFO - controller - request() - Controller request: get_passphrase
2024-05-16 15:13:53 - [CardConnector.py:1491] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - In card_encrypt_secure_channel()
2024-05-16 15:13:53 - [CardConnector.py:1502] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - Plaintext C-APDU: B0 42 00 00 06 * * * * * *
2024-05-16 15:13:53 - [SecureChannel.py:63] - DEBUG - pysatochip.pysatochip.SecureChannel - encrypt_secure_channel() - In encrypt_secure_channel()
2024-05-16 15:13:53 - [CardConnector.py:73] - DEBUG - pysatochip.pysatochip.CardConnector - update() - > B0 82 00 00 38 D6 9F 7D 4D 95 F6 A5 BC AF 33 30 F3 00 00 00 01 00 10 D3 5D 2C EA ED 28 CD B2 48 07 61 6E 83 0B 1B 48 00 14 A4 03 5A 9A 13 A0 29 C3 1B 76 D6 5D 5B DF A0 FE 6F 89 25 BB
2024-05-16 15:13:53 - [CardConnector.py:76] - DEBUG - pysatochip.pysatochip.CardConnector - update() - < [] 9C 0C
2024-05-16 15:13:53 - [controller.py:94] - INFO - controller - request() - Controller request: show, ERROR
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 332, in <lambda>
    command=lambda: self.controller.request("change_pin"),
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
    reply = method_to_call(*args)
  File "/home/satochip/Documents/github/satochip_utils/view.py", line 793, in change_pin
    self.controller.cc.card_verify_PIN()
  File "/home/satochip/Documents/github/satochip_utils/pysatochip/pysatochip/CardConnector.py", line 1354, in card_verify_PIN
    self.client.request('show, ERROR', msg)
  File "/home/satochip/Documents/github/satochip_utils/controller.py", line 96, in request
    method_to_call = getattr(self.view, request_type)
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 2345, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'show, ERROR'
```

**Comment by Tech-Aware** [comment]
Normally, it's fixed !!

**Comment by Tech-Aware** [comment]
> error: " AttributeError: '_tkinter.tkapp' object has no attribute 'show, ERROR' "
> 
> stack trace:
> ```
> 2024-05-16 15:13:47 - [controller.py:94] - INFO - controller - request() - Controller request: change_pin
> 2024-05-16 15:13:47 - [CardConnector.py:1310] - INFO - pysatochip.pysatochip.CardConnector - card_verify_PIN() - In card_verify_PIN
> 2024-05-16 15:13:47 - [controller.py:274] - INFO - controller - PIN_dialog() - In PIN dialog
> 2024-05-16 15:13:47 - [controller.py:94] - INFO - controller - request() - Controller request: get_passphrase
> 2024-05-16 15:13:53 - [CardConnector.py:1491] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - In card_encrypt_secure_channel()
> 2024-05-16 15:13:53 - [CardConnector.py:1502] - INFO - pysatochip.pysatochip.CardConnector - card_encrypt_secure_channel() - Plaintext C-APDU: B0 42 00 00 06 * * * * * *
> 2024-05-16 15:13:53 - [SecureChannel.py:63] - DEBUG - pysatochip.pysatochip.SecureChannel - encrypt_secure_channel() - In encrypt_secure_channel()
> 2024-05-16 15:13:53 - [CardConnector.py:73] - DEBUG - pysatochip.pysatochip.CardConnector - update() - > B0 82 00 00 38 D6 9F 7D 4D 95 F6 A5 BC AF 33 30 F3 00 00 00 01 00 10 D3 5D 2C EA ED 28 CD B2 48 07 61 6E 83 0B 1B 48 00 14 A4 03 5A 9A 13 A0 29 C3 1B 76 D6 5D 5B DF A0 FE 6F 89 25 BB
> 2024-05-16 15:13:53 - [CardConnector.py:76] - DEBUG - pysatochip.pysatochip.CardConnector - update() - < [] 9C 0C
> 2024-05-16 15:13:53 - [controller.py:94] - INFO - controller - request() - Controller request: show, ERROR
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
>     return self.func(*args)
>   File "/home/satochip/Documents/github/satochip_utils/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
>     self._command()
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 332, in <lambda>
>     command=lambda: self.controller.request("change_pin"),
>   File "/home/satochip/Documents/github/satochip_utils/controller.py", line 97, in request
>     reply = method_to_call(*args)
>   File "/home/satochip/Documents/github/satochip_utils/view.py", line 793, in change_pin
>     self.controller.cc.card_verify_PIN()
>   File "/home/satochip/Documents/github/satochip_utils/pysatochip/pysatochip/CardConnector.py", line 1354, in card_verify_PIN
>     self.client.request('show, ERROR', msg)
>   File "/home/satochip/Documents/github/satochip_utils/controller.py", line 96, in request
>     method_to_call = getattr(self.view, request_type)
>   File "/usr/local/lib/python3.8/tkinter/__init__.py", line 2345, in __getattr__
>     return getattr(self.tk, attr)
> AttributeError: '_tkinter.tkapp' object has no attribute 'show, ERROR'
> ```

It is ?
